### ISSUE TITLE
Plattform?

### ISSUE THREAD

**Issue by pr0nopoly** [AldebaranIndustries/scratchpad#1]
Wie sieht es aus? Gehen wir spezifisch auf die Betriebssysteme oder laufen wir im Browser?

Ich wäre für den Browser, bin aber für andere Vorschläge auch offen.
Die Vorteile wären:
- Einfaches Insta-Deployment (kein Versionsabfick)
- Läuft überall

**Comment by xDreamCoding** [comment]
Ich hatte im pr0 schon mal in den Kommentaren LibGDX erwähnt. Damit hab ich schon einiges gemacht und das läuft auf allen Plattformen, allerdings eher Richtung Desktop und Android. Aber ist eben Java und ich meine gelesen zu haben das du da etwas gegen hast.

edit: Wieso sind hier jetzt eigentlich 2 Projekte offen?

**Comment by FlaShG** [comment]
Hallo!

Ich oute mich direkt mal als Unity-fanboy. Läuft auch überall.
Ist natürlich proprietär und wasnichtalles, macht's aber so viel entspannter...

**Comment by pr0nopoly** [comment]
Ich hab keine Erfahrung mit Unity, allerdings sehe ich dort den großen Vorteil, dass wir schnelle Ergebnisse hätten. Dafür würde ich mich damit auch beschäftigen.
Ich bin versiert in C# und in letzter Zeit mache ich viel mit TypeScript (bin kein Fan von purem JS).

**Comment by FlaShG** [comment]
Das JavaScript in Unity hat auch fast gar nichts mehr mit Javascript zu tun. C# ist trotzdem nicht grundlos die beliebtere Sprache.

**Comment by pr0nopoly** [comment]
Habe mit C# was Spieleentwicklung betrifft bisher nur etwas mit XNA und MonoGame rumgespielt.

**Comment by ghost** [comment]
Ich kann auch Grundkenntnisse in Unity, XNA und C# anbieten, deshalb währe das mein Fall. Ich muss aber dazu gestehen, dass ich nicht professionell programmiere, sondern eher Hobby mäßig, würde mich deshalb nicht als Überflieger betrachten. Jedoch kriege ich das was ich will auch zum laufen, auch wenn es bestimmt schöner geht.
In Sachen Java/JS muss ich leider komplett passen. Könnte höchstens noch mit C++ oder Assembler etwas anfangen, jedoch sind diese Sprachen, bei diesem Projekt nicht wirklich vom Nutzen.
Was für Unity sprechen würde ist die einfache Umsetzbarkeit eines Spiels auf allen Plattformen. Und das in beiden Sprachen C# und JS. Ich kann allerdings keine Erfahrungen mitteilen, wie das als gemeinschaftliches Projekt geht. Allerdings ist die Umsetzung eines Spiel doch "relativ" einfacher in Unity, weil einem doch schon eine menge Arbeit abgenommen wird, im Vergleich zu irgendwelchen Framworks.

**Comment by xDreamCoding** [comment]
Gut, ich wollte mich sowieso mal etwas mit Unity vertraut machen. Und wenn ein Teil schon etwas Erfahrung damit hat macht es das auch einfacher.

**Comment by ghost** [comment]
Bleibt nur noch die Frage wie mann das als gemeinschaftliches Projekt aufzieht. Hat jemand da generelle Erfahrung, oder eine Idee ? Was das angeht bin ich völlig neu in der Materie.

**Comment by FlaShG** [comment]
Ich kann ein leeres Unity-Projekt mit vernünftiger gitignore anlegen.

Wenn man Szenen mergen möchte - dafür arbeite ich seit einiger Zeit an einem Tool: https://github.com/FlaShG/GitMerge-for-Unity
Würde ich dann als Subprojekt einfügen.

Eine Sache wäre dann noch: Für Assets lohnt ja in der Regel eine andere Verwwaltung als git. Bläht sich ja recht schnell auf. Ideen?

**Comment by pr0nopoly** [comment]
Was bietet Unity den für Plattformen an? Web? Auch ohne Plugin? Mit/ohne C#? Wie ist das mit Git? Kann man das mit Unity einfach benutzen oder gibt das abfuck mit irgendwelchen Mergeconflicts?

Bei Browsern hat man sogar mittlerweile ne Gamepad-API, die man mit JS (oder wie ich bisher mit TypeScript) verwenden kann. Hat auch was, aber ich denke mal wir wollen keine Engine von grund auf schreiben, weshalb wir da was bräuchten. Habe mit pixijs fürs Rendering etwas Erfahrung, aber es gict sicherlich auch vollwertigere Sachen, die auch Physik und so mit bei haben. 
Würde im Browser laufen und auch als standalone-Anwendung mit Node-Webkit.

Wwas genau ist mit Java? Ich halte es für Krebs (wie jeder andere, der mal ernsthaft mit C# gearbeitet hat). Wenn Ihr es aber bevorzugen würdet, wäre ich auch dazu bereit. Bietet die LibGDX auch Physik?

Edit:
Ich würde sagen die Assets sollten wir separate aufbewahren - vielleicht ein eigens Repo? Ist zwar Git-Vergewaltigung, aber für's erste gehts erstmal, denk ich.

**Comment by xDreamCoding** [comment]
Bei LibGDX entwickelt man das Spiel nativ auf dem Desktop (schnelle Entwicklungszyklen, da man zB nicht immer wieder aufs Smartphone deployen und auch nicht mit dem hässlichen Emulator rumeiern muss) und den selben Code kann man dann mit minimalem Aufwand auf Android/Iphone und im Browser (über GWT) laufen lassen.
Ja LibGDX hat Box2D für 2D und Bullet für 3D Physik integriert.

Edit: finde übrigens C# auch schöner als Java

**Comment by FlaShG** [comment]
Du codest immer in C#/UnityScript/Boo und er exportiert auf alles. Ab Unity 5 auch nach WebGL ohne Plugin.

**Comment by ghost** [comment]
Wie gesagt denke ich das Unity viel Arbeit einspart, da man sich um vieles keine Gedanken machen muss, außerdem funktioniert es auf alles Plattformen. Das mit dem teilen von Szenen und Assets ist ziemlich genial und auch sehr hilfreich. Denn dort hatte ich ein großes Problem gesehen. Danke dafür FlaShG.

**Comment by pr0nopoly** [comment]
Ich weiß jetzt nicht, wie viele her noch zukommen werden, aber man könnte ja mal irgendwo festhalten, wer jetzt für was ist.

Edit:
Ich schaue mir gerade mal diese Serie an:
https://www.youtube.com/playlist?list=PLoFAh-iWxtU4ESFh3YnMvQVXlEiRdTEBP
Sieht durchaus interessant und auch relativ simpel aus.

**Comment by ghost** [comment]
Ok ich bin ganz klar für Unity und C#. Dort habe ich die meiste Erfahrung und ist meiner Meinung auch die beste Möglichkeit, zur Realisierung.

**Comment by FlaShG** [comment]
Assets in einem Extra git-Repo finde ich gar nicht schlecht. Wenn das mal zu dick wird, legt man einfach ein neues an.

Das leere Unity-Projekt ist fertig. Ich bräuchte dann mal Schreibrechte im "richtigen" Repo. Alle anderen, vermute ich, auch.

**Comment by RazielGhul** [comment]
Dein Invite ist raus, warst bis jetzt anscheinend nochnicht öffentlich in der Organisation drin.

**Comment by RazielGhul** [comment]
Btw. Bin recht unerfahren, was Unity etc. angeht. hab mir mal Unity 3d pro runtergeladen, ist da zu empfehlen? C# ist für mich auch relativ neu, aber hab' gute Grundlagen was Java , c++ und c angeht, sollte also nicht alzu lang dauern, bis ich mit C# auf wendenbarem Niveau bin. Kannst du irgendwelche Literatur empfehlen, was C# & Unity Spieleentwicklung angeht?

**Comment by FlaShG** [comment]
Für das, was wir tun, brauchst du keine Pro. Die brauchst du erst, wenn du dicke Postprocessing-Shader haben willst oder bereits ordentlich Gewinn mit dem Spiel gemacht hast.

Ich finde als Lernressource die offiziellen Tutorials ganz gut: http://unity3d.com/learn/tutorials/modules
(weiter unten, "topics").

Grundsätzlich ist zum Scripten zu sagen: Unity setzt auf ein Entity-Component-System (ECS) anstatt auf Vererbungshierarchien. Ich werde einfach mal Cha0s und seine Kamera einbauen, sobald wir das mit den Grafik-Assets aufgesetzt haben.

P.S. Ich war einfach nur zu blöd, die Einladung anzunehmen.

**Comment by FlaShG** [comment]
So, da heben wir einen Cha0s, der sich bewegen kann. Habe versucht, das aussagekräftig zu kommentieren. Vergesst nicht "git submodule update" wegen der Grafik.
Wollen wir dann eigentlich issuetechnisch zum anderen Repo rüberwechseln? Gefühlt ist das mit der Plattform ja geklärt.

**Comment by pr0nopoly** [comment]
UNity 5 ist ja jetzt draußen. HIlft uns das? Habe gehört, dass man jetzt WebGL hat, also das Spiel im Browser ohne Plugin?

**Comment by FlaShG** [comment]
Jo, das ist ganz witzig. Für die meisten Leute viel wichtiger ist, dass dem Editor jetzt keine Features mehr in der kostenlosen Version fehlen. Gibt ein paar Einschränkungen, aber Grafik und Sound gehören da jetzt wohl nicht mehr zu.

Einen WebGL-Build können wir auf jeden Fall machen, tut nicht weh.
