### ISSUE TITLE
Worum gehts?

### ISSUE THREAD

**Issue by xDreamCoding** [AldebaranIndustries/scratchpad#2]
Also gehts jetzt hier um die Reise nach Aldebaran oder die pr0-app? oder um beides?

**Comment by pr0nopoly** [comment]
Vorerst nur um die Reise nach Aldebaran, denk ich.

**Comment by xDreamCoding** [comment]
Ja finde auch, dass die bestehende Mobilebrowser-Version vorerst vollkommen ausreichend ist.
