### ISSUE TITLE
Git + Unity

### ISSUE THREAD

**Issue by xDreamCoding** [AldebaranIndustries/scratchpad#7]
Hab jetzt mal Unity runtergeladen, wenn ich das Code- und das Asset-Projekt clone und in Unity öffne kommt da nicht wirklich was funktionstüchtiges.. Muss ich vielleicht vorher ein leeres Projekt erstellen und dann etwas reinkopieren oder was übersehe ich?

**Comment by FlaShG** [comment]
Kann sein, dass da was Fehlt. Im Zweifelsfall neben "Assets" und "ProjectSettings" einfach je einen leeren Ordner "Temp" und "Library" anlegen.

**Comment by xDreamCoding** [comment]
Okay mein Fehler.. das man noch ne Scene öffnen muss, um was angezeigt zu bekommen, wusste ich als Unity Noob natürlich nicht..
